"""
weather/client.py — STUB owned by Member C.

A's code calls get_rainfall() from here. Until C implements it, this returns
a mock payload so the rest of the backend can run without a live API.

DO NOT edit this file (Member A). All changes here belong to Member C.
"""

import logging
from datetime import datetime, timezone

logger = logging.getLogger("weather")

# ---------------------------------------------------------------------------
# Mock rainfall data (simulated; labelled as such in every response)
# ---------------------------------------------------------------------------
_MOCK_NORMAL = {
    "rain_24h_mm": 15.0,
    "forecast_3h_mm": 4.0,
    "data_source": "simulated",
    "data_timestamp": None,  # filled at call time
}

_MOCK_FLOOD = {
    "rain_24h_mm": 95.0,
    "forecast_3h_mm": 22.0,
    "data_source": "simulated",
    "data_timestamp": None,
}


def get_rainfall(lat: float, lng: float, scenario: str = "normal") -> dict:
    """
    Return rainfall data for a location.

    Parameters
    ----------
    lat, lng : float   Coordinates of the point of interest.
    scenario : str     "normal" or "flood"; drives mock values.

    Returns
    -------
    dict with keys: rain_24h_mm, forecast_3h_mm, data_source, data_timestamp
    """
    now_iso = datetime.now(timezone.utc).isoformat()
    base = _MOCK_FLOOD if scenario == "flood" else _MOCK_NORMAL
    result = dict(base)
    result["data_timestamp"] = now_iso
    logger.info(
        "[STUB] get_rainfall(lat=%s, lng=%s, scenario=%s) → mock data", lat, lng, scenario
    )
    return result
